### ISSUE TITLE
Crit System

### ISSUE THREAD

**Issue by qnf613** [qnf613/Project_DimensionGate#23]
Make a critical strike system which applied bonus damage with possibility.

- [x] system
- [x] UI

**Comment by ErRibeiro** [comment]
I added a crit system. The current system assigns the bullet to be a critical bullet or not. (Some weapons act different, like the lucky comet)

This is not 100% finished yet.
Weapons which do not work with the crit system are- Poison flask and rocket launcher.
These weapons work differently from other and I will need to make something more specific for them.

**Comment by ErRibeiro** [comment]
When a critical hit lands on a target, the number will be yellow instead of red. Also, due to higher damage, the text size will be bigger.
