### ISSUE TITLE
Upgrade Items

### ISSUE THREAD

**Issue by qnf613** [qnf613/Project_DimensionGate#24]
Make the actual upgrade functions for each weapon.
Each weapon's upgrade per level should be different. 
Ex) level 2 for magic arrow is increase attack speed, level 2 for sharp shooter is increase damage.
Also, each weapon should get unique function when it hit max upgrade level

**Comment by ErRibeiro** [comment]
Weapons can now upgrade differently depending on the settings of the weapon.
You can currently upgrade damage, crit damage and crit chance.

TODO in the future : Unique upgrades when the weapon hits max rank.

**Comment by ErRibeiro** [comment]
BUGFIX : 
Weapons now upgrade from level up rewards too.
