### ISSUE TITLE
Find/Create Tileset + level layout

### ISSUE THREAD

**Issue by Vantrono** [qnf613/Project_DimensionGate#25]
- [x] Find/Create Tileset
- [x] Slice and implement tiles 
- [x] Implement into level 
First level Mythical Forest complete!

**Comment by ErRibeiro** [comment]
NEW LEVEL !!!!

Dungeon style map added. 
I still need to finish the boundaries and other functionalities but the art/layout is done

**Comment by Vantrono** [comment]
> NEW LEVEL !!!!
> 
> Dungeon style map added. I still need to finish the boundaries and other functionalities but the art/layout is done

Added Boundaries for player and AI
*Fixed a few sprite issues as well

**Comment by ErRibeiro** [comment]
NEW MAP!!!!
Mountain top map!
![image](https://user-images.githubusercontent.com/71297100/165878988-403c9617-8dd9-42b6-a692-6a652de44400.png)

![image](https://user-images.githubusercontent.com/71297100/165878957-157dc282-abc7-4c9c-ab9a-495105287f65.png)

**Comment by Vantrono** [comment]
> NEW MAP!!!! Mountain top map! ![image](https://user-images.githubusercontent.com/71297100/165878988-403c9617-8dd9-42b6-a692-6a652de44400.png)
> 
> ![image](https://user-images.githubusercontent.com/71297100/165878957-157dc282-abc7-4c9c-ab9a-495105287f65.png)

Added Boundaries for player and AI
Added an extra bridge so players can pass and enemies wouldn't get stuck
