### ISSUE TITLE
Player

### ISSUE THREAD

**Issue by qnf613** [qnf613/Project_DimensionGate#3]
Make a player character that can 2D top down view-move, look direction where mouse cursor is pointing, and has stats that can work with weapons

- [x] Movement
- [x] Look direction of cursor
- [x] Has stats: (list of items can be changed in the future)
   - [x] HP
   - [ ] Damage
   - [x] Move Speed
   - [ ] Attack Speed
   - [ ] etc.

**Comment by Vantrono** [comment]
Finished coding the movement and the player can shoot at any direction. 
Coded variable move speed and HP stat. 
We decided to not do damage and attack speed.
