### ISSUE TITLE
Monster

### ISSUE THREAD

**Issue by qnf613** [qnf613/Project_DimensionGate#4]
Make a base monster that can 2D top down view-move, look direction of player, continuously move to the player, and has stats

- [x] Movement
- [x] Look direction of cursor
- [x] Follow to attack the player
- [x] Has stats: (list of items can be changed in the future)
   - [x] HP
   - [x] Damage
   - [x] Move Speed
   - [x] Pathfinding

**Comment by Vantrono** [comment]
Pathfinding is now finished for Enemy AI. 
Added a few lines of code onto Astar script to adjust so that player is found on spawn.
