### ISSUE TITLE
SFXs

### ISSUE THREAD

**Issue by qnf613** [qnf613/Project_DimensionGate#8]
make SFXs for game
it could take a while to do the whole list of things (and listed items will keep adding)
 - [x] Player walk
 - [x] Player get hit
 - [x] Portal
 - [x] Weapons
      - [x] Magic arrow 
      - [x] Poison
      - [x] Sword
      - [x] Comet (orbital weapon)

**Comment by Csalazar7120** [comment]
> make SFXs for game it could take a while to do the whole list of things (and listed items will keep adding)
> 
> * [x]  Player walk
> * [x]  Player get hit
> * [x]  Portal
> * [x]  Weapons
>   
>   * [x]  Magic arrow
>   * [x]  Poison
>   * [x]  Sword
>   * [x]  Comet (orbital weapon)
>   * [x]  Sniper
>   * [x]  Rocket Launcher
>   * [x]  Crits
>
>   * [x]  Ambience (forest)
